#!/bin/bash

: ${LOGFILE:=/tmp/install_hue.log}
: ${DEBUG:=1}

: ${HUE_VERSION:=3.7.1}


install-hue() {
  yum -y install ant asciidoc cyrus-sasl-devel cyrus-sasl-gssapi gcc gcc-c++ krb5-devel libtidy libxml2-devel libxslt-devel mysql mysql-devel openldap-devel python-devel sqlite-devel wget sudo
  echo "JAVA_HOME=$JAVA_HOME" >> /etc/environment 
  wget http://mirror.olnevhost.net/pub/apache/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz
  tar xf apache-maven-3.0.5-bin.tar.gz
  mv apache-maven-3.0.5  /usr/local/apache-maven
  export M2_HOME=/usr/local/apache-maven
  export M2=$M2_HOME/bin 
  export PATH=$M2:$PATH  
  wget http://students.mimuw.edu.pl/~mz292739/hue-$HUE_VERSION-bin.tar
  tar -xzf hue-$HUE_VERSION-bin.tar
  mv hue /usr/local
  useradd hue
  chown -R hue:hue /usr/local/hue
  HOSTNAME=`hostname`.node.consul
  HUE_INI=/usr/local/hue/desktop/conf/hue.ini
  RAND_TEXT=`tr -dc a-z </dev/urandom | head -c 50`
  sed -i "s/fs_defaultfs=hdfs:\/\/localhost:8020/fs_defaultfs=hdfs:\/\/${HOSTNAME}:8020/g" ${HUE_INI}
  /usr/local/hue/desktop/conf/hue.ini
  sed -i "s/## webhdfs_url=http:\/\/localhost:50070\/webhdfs\/v1/webhdfs_url=http:\/\/${HOSTNAME}:50070\/webhdfs\/v1/g" ${HUE_INI}
  sed -i "s/## resourcemanager_host=localhost/resourcemanager_host=${HOSTNAME}/g" ${HUE_INI}
  sed -i "s/## resourcemanager_port=8032/resourcemanager_port=8050/g" ${HUE_INI}
  sed -i "s/## resourcemanager_api_url=http:\/\/localhost:8088/resourcemanager_api_url=http:\/\/${HOSTNAME}:8088/g" ${HUE_INI}
  sed -i "s/## proxy_api_url=http:\/\/localhost:8088/proxy_api_url=http:\/\/${HOSTNAME}:8088/g" ${HUE_INI}
  sed -i "s/# history_server_api_url=http:\/\/localhost:19888/history_server_api_url=http:\/\/${HOSTNAME}:19888/g" ${HUE_INI}
  sed -i "s/## oozie_url=http:\/\/localhost:11000\/oozie/oozie_url=http:\/\/${HOSTNAME}:11000\/oozie/g" ${HUE_INI}
  sed -i "s/## hive_server_host=localhost/hive_server_host=${HOSTNAME}/g" ${HUE_INI}
  sed -i "s/## app_blacklist=/app_blacklist=impala,security,spark,hbase/g" ${HUE_INI}
  sed -i "s/secret_key=/secret_key=${RAND_TEXT}/g" ${HUE_INI}
}

main(){
  debug "$(date) install Apache HUE event triggered."
  install-hue
  debug "$(date) installing Apache HUE done."
}

debug(){
  [[ "$DEBUG" ]] && echo "[DEBUG] $*" >> $LOGFILE
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
