#!/bin/bash

: ${LOGFILE:=/tmp/install_hue.log}
: ${DEBUG:=1}
: ${HUE_VERSION:=3.7.1}


install-hue() {
  yum -y install ant asciidoc cyrus-sasl-devel cyrus-sasl-gssapi gcc gcc-c++ krb5-devel libtidy libxml2-devel libxslt-devel mysql mysql-devel openldap-devel python-devel sqlite-devel wget
  echo "JAVA_HOME=$JAVA_HOME" >> /etc/environment 
  wget http://mirror.olnevhost.net/pub/apache/maven/maven-3/3.0.5/binaries/apache-maven-3.0.5-bin.tar.gz
  tar xf apache-maven-3.0.5-bin.tar.gz
  mv apache-maven-3.0.5  /usr/local/apache-maven
  export M2_HOME=/usr/local/apache-maven
  export M2=$M2_HOME/bin 
  export PATH=$M2:$PATH  
  #wget https://dl.dropboxusercontent.com/u/730827/hue/releases/$HUE_VERSION/hue-$HUE_VERSION.tgz
  #tar -xzf hue-$HUE_VERSION.tgz
  #cd hue-$HUE_VERSION
  #make install
  wget http://students.mimuw.edu.pl/~mz292739/hue-$HUE_VERSION-bin.tar
  tar -xzf hue-$HUE_VERSION-bin.tar
  mv hue /usr/local
  useradd hue
  chown -R hue:hue /usr/local/hue
  HADOOP_USER_NAME=hdfs hdfs dfs -mkdir /user/hue
  HADOOP_USER_NAME=hdfs hdfs dfs -chown hue:hue /user/hue
  HADOOP_USER_NAME=hdfs hdfs dfs -mkdir /user/root
  HADOOP_USER_NAME=hdfs hdfs dfs -chown root:root /user/root
  wget http://students.mimuw.edu.pl/~mz292739/runHue.sh
  chmod +x ./runHue.sh
  atd
  at -f ./runHue.sh now + 5 min
}

main(){
  debug "$(date) install Apache HUE event triggered."
  install-hue
  debug "$(date) installing Apache HUE done."
}

debug(){
  [[ "$DEBUG" ]] && echo "[DEBUG] $*" >> $LOGFILE
}

[[ "$0" == "$BASH_SOURCE" ]] && main "$@"
